# Generated by Django 4.2.8 on 2024-12-10 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="id_driver",
            new_name="driver",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="id_rider",
            new_name="rider",
        ),
        migrations.RenameField(
            model_name="rideevent",
            old_name="id_ride",
            new_name="ride",
        ),
    ]
