# Generated by Django 4.2.8 on 2024-12-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_rename_id_driver_ride_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rideevent",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ride_events",
                to="rides.ride",
            ),
        ),
    ]
